[package]
name = "soroban-fib-faucet-contract"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "0.9.2" }

[dev_dependencies]
soroban-sdk = { version = "0.9.2", features = ["testutils"] }
